### ISSUE TITLE
戳这里

### ISSUE THREAD

**Issue by chainsx** [Erblocker/YRSSF#5]
你的意思是说，睿易派激活了knox后就有su权限了？
不然怎么chmod 000。。。。。
还有，通过setting name=可以更改设置吗？
如果可以，具体怎么设。

**Comment by cgoxopx** [comment]
su平板的刷机包里面自带。

**Comment by chainsx** [comment]
！？
什么意思？

**Comment by cgoxopx** [comment]
我只知道睿易平板root过，具体su的位置……不知道

**Comment by chainsx** [comment]
那。。。。。
设备状态还是官方。。。。。。
是不是knox给的权限？

**Comment by cgoxopx** [comment]
不清楚了

**Comment by chainsx** [comment]
你是怎么知道我们的平板root过的。。。
是看代码吗？
。。。。。。。。。。。
不过找遍了/都没有找到su
echo $PATH查看环境变量的目录也没有。。。
不过，，我安装了busybox

**Comment by cgoxopx** [comment]
因为睿易派调用了iptables

**Comment by cgoxopx** [comment]
在平板上发现了 `su -c "iptables……"` 这样的shell脚本

**Comment by chainsx** [comment]
啊啊啊啊啊!!!!!!!!!!!
那么，，，，，，
su是不是被利用以后被移除了。。。
用Kingroot时一直卡在1%的地方。

**Comment by chainsx** [comment]
不过。。。
平板自带iptables命令。
执行的话，，，
会有以下提示：
~$ iptables --list-rules
iptables v1.4.20: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by chainsx** [comment]
有root为何不用。。。。
是因为怕三星告吗？
