### ISSUE TITLE
关于YRSSF安卓项目

### ISSUE THREAD

**Issue by chainsx** [Erblocker/YRSSF#6]
飞哥，我最近在联系人帮你做YRSSF的安卓版，请近期内准备好相关工作

**Comment by cgoxopx** [comment]
?

**Comment by cgoxopx** [comment]
我不太会写android.mk啊

**Comment by chainsx** [comment]
我的意思是说，
你看看AndroPHP（或者我改的Pandora-magicbox安卓版）
其实就是在Linux ARM上编译好的二进制可执行文件，
再加依赖库，打包成apk，
就在安卓上运行了。
你觉得呢？

**Comment by cgoxopx** [comment]
可以这么弄。再加个webview，指向http://127.0.0.1:1215 ，就是真正的山寨睿易派了。    
不过Android的webview怎么开websocket啊？我找了好久没找到。  
YRSSF的直播需要websocket支持。
