### ISSUE TITLE
!!!!!!!!!!!!

### ISSUE THREAD

**Issue by chainsx** [Erblocker/YRSSF#7]
关于那个更新的问题，
我觉得你想办法在YRSSF使用的httpd里加ssl，
再反代资源端口，切换账号，
应该没什么问题
还有其他的。。。。。

**Comment by chainsx** [comment]
我建议在YRSSF启动是加一个后台运行的参数，
例如
./YRSSF --daemon
还有在运行界面加一个退出的选项，
Press Ctrl + C to interrupt

**Comment by cgoxopx** [comment]
前30秒要加载机器学习模型。所以ctrl+c过后要30秒才退出
